apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - ap-northeast-2a
  - ap-northeast-2c
metadata:
  name: test-cluster
  region: ap-northeast-2
  version: "1.29"
iam:
  withOIDC: true
vpc:
  cidr: 10.10.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
managedNodeGroups:
  - name: default
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    instanceType: t3.large
    privateNetworking: true
    releaseVersion: "1.29.0-20240129"
    updateConfig:
      maxUnavailablePercentage: 50
